version: 2
updates:
  - package-ecosystem: "npm"  
    directory: "/"             # Using root for both Client and Server
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
